class CarCompanies{
public static void main(String[] args){
	String carCompany1="Maruti Suzuki";
	System.out.println(carCompany1);
	String carCompany2="Hyundai";
	System.out.println(carCompany2);
	String carCompany3="Tata Motors";
	System.out.println(carCompany3);
	String carCompany4="Mahindra";
	System.out.println(carCompany4);
	String carCompany5="Kia";
	System.out.println(carCompany5);
	String carCompany6="Toyota";
	System.out.println(carCompany6);
	String carCompany7="Honda";
	System.out.println(carCompany7);
	String carCompany8="MG Motor";
	System.out.println(carCompany8);
	String carCompany9="Renault";
	System.out.println(carCompany9);
	String carCompany10="Volkswagen";
	System.out.println(carCompany10);
	String carCompany11="Skoda";
	System.out.println(carCompany11);
	String carCompany12="Nissan";
	System.out.println(carCompany12);
	String carCompany13="Citroen";
	System.out.println(carCompany13);
	String carCompany14="Jeep";
	System.out.println(carCompany14);
	String carCompany15="Force Motors";
	System.out.println(carCompany15);
	String carCompany16="Isuzu";
	System.out.println(carCompany16);
	String carCompany17="BYD";
	System.out.println(carCompany17);
	String carCompany18="Pravaig";
	System.out.println(carCompany18);
	String carCompany19="Mercedes-Benz";
	System.out.println(carCompany19);
	String carCompany20="BMW";
	System.out.println(carCompany20);
	String carCompany21="Audi";
	System.out.println(carCompany21);
	String carCompany22="Jaguar Land Rover";
	System.out.println(carCompany22);
	String carCompany23="Volvo";
	System.out.println(carCompany23);
	String carCompany24="Lexus";
	System.out.println(carCompany24);
	String carCompany25="Mini";
	System.out.println(carCompany25);
	String carCompany26="Porsche";
	System.out.println(carCompany26);
	String carCompany27="Ferrari";
	System.out.println(carCompany27);
	String carCompany28="Lamborghini";
	System.out.println(carCompany28);
	String carCompany29="Rolls Royce";
	System.out.println(carCompany29);
	String carCompany30="Bentley";
	System.out.println(carCompany30);
	String carCompany31="Maserati";
	System.out.println(carCompany31);
	String carCompany32="Aston Martin";
	System.out.println(carCompany32);
	String carCompany33="MCLaren";
	System.out.println(carCompany33);
	
}
}