class Dances{
public static void main(String[] args){
	String danceType="Bharatanatyam";
	System.out.println(danceType);
	danceType="Kathak";
	System.out.println(danceType);
	danceType="Kathakali";
	System.out.println(danceType);
	danceType="Kuchipudi";
	System.out.println(danceType);
	danceType="Odissi";
	System.out.println(danceType);
	danceType="Manipuri";
	System.out.println(danceType);
	danceType="Mohiniyattam";
	System.out.println(danceType);
	danceType="Sattriya";
	System.out.println(danceType);
	danceType="Bhangra";
	System.out.println(danceType);
	danceType="Garba and Dandiya";
	System.out.println(danceType);
	danceType="Ghoomar";
	System.out.println(danceType);
	danceType="Bihu";
	System.out.println(danceType);
	danceType="Chhau";
	System.out.println(danceType);
	danceType="Yakshagana";
	System.out.println(danceType);
	danceType="Koli";
	System.out.println(danceType);
	danceType="Rouf";
	System.out.println(danceType);
	danceType="Dollu Kunitha";
	System.out.println(danceType);
	danceType="Veeragase";
	System.out.println(danceType);
	danceType="Kummi";
	System.out.println(danceType);
	danceType="Kolannalu(Stick Dance)";
	System.out.println(danceType);
	danceType="Perini Shivatandavam";
	System.out.println(danceType);
	danceType="Karagattam";
	System.out.println(danceType);
	danceType="Theyyam";
	System.out.println(danceType);
	danceType="Bhuta Kola";
	System.out.println(danceType);
	danceType="Gond Dance";
	System.out.println(danceType);
	danceType="Santhal Dance";
	System.out.println(danceType);
	danceType="Hojagiri";
	System.out.println(danceType);
	danceType="Cheraw(Bamboo Dance)";
	System.out.println(danceType);
	danceType="Naga Tribal Dances";
	System.out.println(danceType);
	danceType="Bhagoria";
	System.out.println(danceType);
	danceType="Chhau";
	System.out.println(danceType);
	danceType="Thang Ta";
	System.out.println(danceType);
	danceType="Kalaripayyattu";
	System.out.println(danceType);
	danceType="Paika";
	System.out.println(danceType);	
    danceType="Dumhal";
	System.out.println(danceType);
	danceType="Losar Shona Chuksam";
	System.out.println(danceType);
	danceType="Hornbill Festival Dances";
	System.out.println(danceType);
	danceType="Wangala";
	System.out.println(danceType);
	
}
}