
class Movies{
	public static void main(String[] args){
		String movies="Appu";
		System.out.println(movies);
		movies="Abhi";
		System.out.println(movies);
		movies="Veer Kannadiga";
		System.out.println(movies);
		movies="Akasha";
		System.out.println(movies);
		movies="Namma Basava";
		System.out.println(movies);
		movies="Ajay";
		System.out.println(movies);
		movies="Arasu";
		System.out.println(movies);
		movies="Milana";
		System.out.println(movies);
		movies="Bindaas";
		System.out.println(movies);
		movies="Vamshi";
		System.out.println(movies);
		movies="Raaj-the showman";
		System.out.println(movies);
		movies="Raam";
		System.out.println(movies);
		movies="Prithvi";
		System.out.println(movies);
		movies="Jackie";
		System.out.println(movies);
		movies="Hudugaru";
		System.out.println(movies);
		movies="Paramathma";
		System.out.println(movies);
		movies="Anna Band";
		System.out.println(movies);
		movies="Yaare Koogadali";
		System.out.println(movies);
		movies="Ninindale";
		System.out.println(movies);
		movies="power";
		System.out.println(movies);
		movies="Mytri";
		System.out.println(movies);
		movies="Rana Vikrama";
		System.out.println(movies);
		movies="Chakravyuha";
		System.out.println(movies);
		movies="Doddmane Hudga";
		System.out.println(movies);
		movies="Raajakumara";
		System.out.println(movies);
		movies="Anjani Putra";
		System.out.println(movies);
		movies="Yuvarathnaa";
		System.out.println(movies);
		movies="Natasaarvabhowma";
		System.out.println(movies);
		movies="James";
		System.out.println(movies);
		movies="Gandhada Gudi";
		System.out.println(movies);
		movies="Maurya";	
		System.out.println(movies);
	}
}