class Artist{
public static void main(String[] args){
	String artist="Raja Ravi Varma";
	System.out.println(artist);
	artist="Amrita Sher-gil";
	System.out.println(artist);
	artist="Abanindranath Tagore";
	System.out.println(artist);
	artist="Rabindranath Tagore";
	System.out.println(artist);
	artist="Nandalal Bose";
	System.out.println(artist);
	artist="Jamini Roy";
	System.out.println(artist);
	artist="Ganganendranath Tagore";
	System.out.println(artist);
	artist="Ramkinkar Baji";
	System.out.println(artist);
	artist="Benode Behari Mukherjee";
	System.out.println(artist);
	artist="Mukul dey";
	System.out.println(artist);
	artist="M F Husain";
	System.out.println(artist);
	artist="S H Raza";
	System.out.println(artist);
    artist="F N Souza";
	System.out.println(artist);
	artist="V S Gaitonde";
	System.out.println(artist);
	
    artist="Tyeb Mehta";
	System.out.println(artist);
	artist="Akbar Padamsee";
	System.out.println(artist);
	artist="Ram Kumar";
	System.out.println(artist);
	artist="Krishen Khanna";
	System.out.println(artist);
    artist="K H Ara";
	System.out.println(artist);
	artist="Sadanand Bakre";
	System.out.println(artist);
	artist="Satish Gujral";
	System.out.println(artist);
	artist="K G Subaramanyam";
	System.out.println(artist);
	artist="Bhupen Khakhar";
	System.out.println(artist);
	artist="Manjit Bawa";
	System.out.println(artist);
	artist="Jogen Chowdhury";
	System.out.println(artist);
	artist="Ganesh Pyne";
	System.out.println(artist);
	artist="Bikash Bhattacharjee";
	System.out.println(artist);
	artist="Arpita Singh";
	System.out.println(artist);
	
	artist="Anjolie Ela Menon";
	System.out.println(artist);
	artist="A Ramachandran";
	System.out.println(artist);
	artist="Gulam Mohammed Sheikh";
	System.out.println(artist);
	artist="Rameshwar Broota";
	System.out.println(artist);
	artist="Laxma Goud";
	System.out.println(artist);
	artist="Thota Vaikuntam";
	System.out.println(artist);
	artist="Nasreen Mohamedi";
	System.out.println(artist);
	artist="Zarina Hashmi";
	System.out.println(artist);
	artist="Anish Kapoor";
	System.out.println(artist);
	artist="Subodh Gupta";
	System.out.println(artist);
	artist="Bharti kher";
	System.out.println(artist);
	artist="Atul Dodiya";
	System.out.println(artist);
	artist="Jitish Kallat";
	System.out.println(artist);
	artist="Reena Saini Kallat";
	System.out.println(artist);
	
	artist="Nalini Malani";
	System.out.println(artist);
	artist="Vivan Sundaram";
	System.out.println(artist);
	artist="Sudhir Patwardhan";
	System.out.println(artist);
	artist="Paresh Maity";
	System.out.println(artist);
	artist="Shilpa Gupta";
	System.out.println(artist);
	artist="Raqib Shaw";
	System.out.println(artist);
	artist="Ravinder Reddy";
	System.out.println(artist);
	artist="N S Harsha";
	System.out.println(artist);
	
}
}