class GreenLineMetro{
  public static void main(String[] args){
	  String metroStation1="Madavara";
	  System.out.println(metroStation1);
	  String metroStation2="Chikkabidarakallu";
	  System.out.println(metroStation2);
	  String metroStation3="Manjunathanagara";
	  System.out.println(metroStation3);
	  String metroStation4="Nagasandra";
	  System.out.println(metroStation4);
	  String metroStation5="Dasarahalli";
	  System.out.println(metroStation5);
	  String metroStation6="Jalahalli";
	  System.out.println(metroStation6);
	  String metroStation7="Peenya Industry";
	  System.out.println(metroStation7);
	  String metroStation8="Peenya";
	  System.out.println(metroStation8);
	  String metroStation9="Goraguntepalya";
	  System.out.println(metroStation9);
	  String metroStation10="Yeshwanthpur";
	  System.out.println(metroStation10);	  
	  String metroStation11="Sandal Soap Factory";
	  System.out.println(metroStation11);
	  String metroStation12="Mahalakshmi";
	  System.out.println(metroStation12);
	  String metroStation13="Rajajinagara";
	  System.out.println(metroStation13);
	  String metroStation14="Mahakavi Kuvempu Road";
	  System.out.println(metroStation14);
	  String metroStation15="Srirampura";
	  System.out.println(metroStation15);
	  String metroStation16="Mantri Square Sampige Road";
	  System.out.println(metroStation16);
	  String metroStation17="Nadaprabhu Kempegowda Station";
	  System.out.println(metroStation17);
	  String metroStation18="Chikkapete";
	  System.out.println(metroStation18);
	  String metroStation19="Krishna Rajedra Market";
	  System.out.println(metroStation19);
	  String metroStation20="National College";
	  System.out.println(metroStation20);
	  
	  String metroStation21="Lalbagh Botanical Garden";
	  System.out.println(metroStation21);
	  String metroStation22="South End Circle";
	  System.out.println(metroStation22);
	  String metroStation23="Jayanagara";
	  System.out.println(metroStation23);
	  String metroStation24="Rashtreeya Vidyalaya Road";
	  System.out.println(metroStation24);
	  String metroStation25="Banashankari";
	  System.out.println(metroStation25);
	  String metroStation26="Jaya Prakash Nagara";
	  System.out.println(metroStation26);
	  String metroStation27="Yelachenahalli";
	  System.out.println(metroStation27);
	  String metroStation28="Konanakunte Cross";
	  System.out.println(metroStation28);
	  String metroStation29="Doddakallasandra";
	  System.out.println(metroStation29);
	  String metroStation30="Vajarahalli";
	  System.out.println(metroStation30);
	  String metroStation31="Thalaghattapura";
	  System.out.println(metroStation31);
	  String metroStation32="Silk Institute";
	  System.out.println(metroStation32);
	 
  }
}