class Vegetable{
public static void main(String[] args){
	String vegetable1="Radish";
	System.out.println(vegetable1);
	String vegetable2="Carrot";
	System.out.println(vegetable2);
	String vegetable3="Turmeric";
	System.out.println(vegetable3);
	String vegetable4="Potato";
	System.out.println(vegetable4);
	String vegetable5="Lady Finger";
	System.out.println(vegetable5);
	String vegetable6="Onion";
	System.out.println(vegetable6);
	String vegetable7="Peas";
	System.out.println(vegetable7);
	String vegetable8="Ginger";
	System.out.println(vegetable8);
	String vegetable9="Tomato";
	System.out.println(vegetable9);
	String vegetable10="Aubergine";
	System.out.println(vegetable10);
	String vegetable11="Brinjal";
	System.out.println(vegetable11);
	String vegetable12="Eggplant";
	System.out.println(vegetable12);
	String vegetable13="Fenugreek Leaf";
	System.out.println(vegetable13);
	String vegetable14="Curry Leaf";
	System.out.println(vegetable14);
	String vegetable15="Bitter Gourd";
	System.out.println(vegetable15);
	String vegetable16="Peppermint";
	System.out.println(vegetable16);
	String vegetable17="Spinach";
	System.out.println(vegetable17);
	String vegetable18="Coriander Leaf";
	System.out.println(vegetable18);
	String vegetable19="Green Onion";
	System.out.println(vegetable19);
	String vegetable20="Bell Pepper";
	System.out.println(vegetable20);
	String vegetable21="Capsicum";
	System.out.println(vegetable21);
	String vegetable22="Green Chilli";
	System.out.println(vegetable22);
	String vegetable23="Black Pepper";
	System.out.println(vegetable23);
	String vegetable24="Red Chilli";
	System.out.println(vegetable24);
	String vegetable25="Chilli";
	System.out.println(vegetable25);
	String vegetable26="Broccoli";
	System.out.println(vegetable26);
	String vegetable27="Red Cabbage";
	System.out.println(vegetable27);
	String vegetable28="Cabbage";
	System.out.println(vegetable28);
	String vegetable29="Cauliflower";
	System.out.println(vegetable29);
	String vegetable30="Ridge Gourd";
	System.out.println(vegetable30);
	String vegetable31="Mustard Greens";
	System.out.println(vegetable31);
	String vegetable32="Spring Onion";
	System.out.println(vegetable32);
	String vegetable33="Yam";
	System.out.println(vegetable33);
	String vegetable34="Corn";
	System.out.println(vegetable34);
	String vegetable35="Maize";
	System.out.println(vegetable35);
	String vegetable36="Cucumber";
	System.out.println(vegetable36);
	String vegetable37="Beetroot";
	System.out.println(vegetable37);
	String vegetable38="Chickpeas";
	System.out.println(vegetable38);
	String vegetable39="Lemon";
	System.out.println(vegetable39);
	String vegetable40="Turnip";
	System.out.println(vegetable40);
	String vegetable41="Kidney beans";
	System.out.println(vegetable41);
	String vegetable42="Mouse Melon";
	System.out.println(vegetable42);
	String vegetable43="Tendil";
	System.out.println(vegetable43);
	String vegetable44="Fava Beans";
	System.out.println(vegetable44);
	String vegetable45="Sweet Potato";
	System.out.println(vegetable45);
	String vegetable46="Lime";
	System.out.println(vegetable46);
	String vegetable47="Arrowroot";
	System.out.println(vegetable47);
	String vegetable48="Bottle Gourd";
	System.out.println(vegetable48);
	String vegetable49="Cluster Beans";
	System.out.println(vegetable49);
	String vegetable50="Mushroom";
	System.out.println(vegetable50);
	String vegetable51="Jackfruit";
	System.out.println(vegetable51);
	String vegetable52="Green Beans";
	System.out.println(vegetable52);
	String vegetable53="Pumpkin";
	System.out.println(vegetable53);
	String vegetable54="Snake Gourd";
	System.out.println(vegetable54);
	String vegetable55="Cordia myxa";
	System.out.println(vegetable55);
	String vegetable56="Natal Plum";
	System.out.println(vegetable56);
	String vegetable57="White Goose Foot";
	System.out.println(vegetable57);
	String vegetable58="Drumstick";
	System.out.println(vegetable58);
	String vegetable59="Celery";
	System.out.println(vegetable59);
	String vegetable60="Ash Gourd";
	System.out.println(vegetable60);
	String vegetable61="Kohlrabi";
	System.out.println(vegetable61);
	String vegetable62="Apple Gourd";
	System.out.println(vegetable62);
	String vegetable63="Amaranthus Dubious";
	System.out.println(vegetable63);
	String vegetable64="Parsnip";
	System.out.println(vegetable54);
	String vegetable65="Raw Banana Flower";
	System.out.println(vegetable65);
	String vegetable66="Raw Papaya";
	System.out.println(vegetable66);
	String vegetable67="Artichoke";
	System.out.println(vegetable67);
	String vegetable68="Green gram";
	System.out.println(vegetable68);
	String vegetable69="Raw Banana";
	System.out.println(vegetable69);
	String vegetable70="Cucumis Utilissimus";
	System.out.println(vegetable70);
	String vegetable71="Drumstick";
	System.out.println(vegetable71);
	String vegetable72="White eggplant";
	System.out.println(vegetable72);
	String vegetable73="Elephant foot yam";
	System.out.println(vegetable73);
	String vegetable74="Colocasia Root";
	System.out.println(vegetable74);
	String vegetable75="Arugula";
	System.out.println(vegetable75);
	String vegetable76="Fennel";
	System.out.println(vegetable76);
	String vegetable77="Gooseberry";
	System.out.println(vegetable77);
	String vegetable78="Bamboo Shoots";
	System.out.println(vegetable78);
	String vegetable79="Colocasia";
	System.out.println(vegetable79);
	String vegetable80="Asparagus";
	System.out.println(vegetable80);
	String vegetable81="Corn";
	System.out.println(vegetable81);
	String vegetable82="Chive";
	System.out.println(vegetable82);
	String vegetable83="Taro";
	System.out.println(vegetable83);
	String vegetable84="Chayote";
	System.out.println(vegetable84);
	String vegetable85="Calabash";
	System.out.println(vegetable85);
	String vegetable86="Bean";
	System.out.println(vegetable86);
	String vegetable87="Radish Pods";
	System.out.println(vegetable87);
	String vegetable88="Purslane";
	System.out.println(vegetable88);
	String vegetable89="Green mustard";
	System.out.println(vegetable89);
	String vegetable90="Hog plum";
	System.out.println(vegetable90);
	String vegetable91="Kale";
	System.out.println(vegetable91);
	String vegetable92="Kohlrabi";
	System.out.println(vegetable82);
	String vegetable93="Lettuce";
	System.out.println(vegetable83);
	String vegetable94="Broad Bean";
	System.out.println(vegetable94);
	String vegetable95="grean pea";
	System.out.println(vegetable95);
	String vegetable96="Salsify";
	System.out.println(vegetable96);
	String vegetable97="Turnip Greens";
	System.out.println(vegetable97);
	String vegetable98="Soyabeans";
	System.out.println(vegetable98);
	String vegetable99="Swiss Chard";
	System.out.println(vegetable99);
	String vegetable100="Radicchio";
	System.out.println(vegetable100);
}
}